config/routes.rb
Rails.application.routes.draw do
  resources :applications
  match 'applications/:id/status', to: 'applications#status', via: 'get', as: :applications_status
  match '/users', to: 'users#index', via: 'get'
  resources :jobs
  resources :companies do
    end
  root to: 'pages#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
  devise_scope :user do
    get 'users/sign_in', to: 'devise/sessions#new'
  end
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
  match '/users/:id', to: 'users#destroy', via: 'delete', as: :user

  resources :profiles, only: [:index, :new, :create, :destroy, :edit, :update] do
  root "profiles#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def index
    @profile = Profile.all
  end

  def new
    @profile = Profile.new
  end

  def edit
  end

  def update
    @profile = Profile.find(params[:id])
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to profiles_path }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to profiles_path
    else
      render "new"
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy
    redirect_to profiles_path
  end

  private
  def profile_params
    params.require(:profile).permit(:no_of_workex_years, :current_company, :user_id, :attachment).merge(user: current_user). merge(name: current_user.name)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<h3>Editing Profile</h3>
<div class="container" id="company-form">
  <div class="row">
    <h4 class="text-center">Please edit the following details</h4>
    <div class="col-sm-offset-4 col-sm-4">
      <%= bootstrap_form_for(Profile.find_by_user_id(current_user.id)) do |form| %>

        <!--<div class="field">-->
          <!--<label for="profile_name">Name</label>-->
          <!--<%= form.text_field :name, id: :profile_name, class: 'form-control'%>-->
        <!--</div>-->
        <div class="field">
          <%= form.label :name %><br />
          <%= form.text_field :name, autofocus: true, autocomplete: Profile.find_by_user_id(current_user.id).name.to_s, disabled: "disabled", class: 'form-control' %>
        </div>

        <div class="field">
          <label for="profile_noofworkexyears">No of Years on Work Experience</label>
          <%= form.text_field :no_of_workex_years, id: :profile_noofworkexyears, class: 'form-control'%>
        </div>

        <div class="field">
          <label for="profile_current_company">Current Company</label>
          <%= form.text_field :current_company, id: :profile_current_company, class: 'form-control'%>
        </div>

        <div class="field">
          <label for="profile_resume">Please Upload Your resume</label>
          <%= form.file_field :attachment %>
        </div>
        <!--<div class="field">-->
        <!--<%= form.label :user_id %>-->
        <!--<%= form.text_field :user_id, id: :profile_user_id %>-->
        <!--</div>-->
        <%= form.submit 'Save Profile', class: 'btn btn-primary btn-lg btn-block'%>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
  <%= link_to 'Back to Profile', profiles_path, class: 'btn btn-warning btn-lg' %>
</div>

app/views/profiles/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>
<h2>Your Profile</h2>
</br>
</br>
<div class="container">
  <div class="row">
<div class="container">
  <div class="container container-fluid">
    <div class="col-sm-offset-9 col-sm-3 right">
      <% if not Profile.exists?(user_id: current_user.id) %>
        <%= link_to "Add your Profile", new_profile_path, class: "btn btn-primary" %>
      <% end %>
    </div>
    </br>
    </br>
    <div class="row">
      <div class="col-sm-offset-4 col-sm-4">
        <p>
          <strong> Name: </strong>
          <% if Profile.exists?(user_id: current_user.id) %>
            <%= Profile.find_by_user_id(current_user.id).name %>
            <% else %>
            <%= current_user.name %>
          <% end %>
        </p>
        <p>
          <strong>No of Years of Work experience:</strong>
          <% if Profile.exists?(user_id: current_user.id) %>
          <%= Profile.find_by_user_id(current_user.id).no_of_workex_years %>
          <% else %>
          <% end %>
        </p>
        <p>
          <strong>Resume:</strong>
          <% if Profile.exists?(user_id: current_user.id) %>
          <%= link_to "Download Resume", Profile.find_by_user_id(current_user.id).attachment_url %>
          <% else %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>
    <% if Profile.exists?(user_id: current_user.id) %>
      <%= link_to 'Edit', edit_profile_path(Profile.find_by_user_id(current_user.id)), class: 'btn btn-primary btn-lg' %>
    <% else %>
    <% end %>
  </div>
</div>

app/views/profiles/new.html.erb
<br>
<br>
<div class="container">
<div class="container container-fluid" id="profile-form">

  <div class="row">
    <h4 class="text-center">Please add profile details</h4>

    <div class="col-sm-offset-4 col-sm-4">
      <%= bootstrap_form_for(@profile) do |form| %>

        <!--<div class="field">-->
          <!--<label for="company_Hq">Name</label>-->
          <!--<%= form.text_field :name, id: :profile_name, class: 'form-control'%>-->
        <!--</div>-->
        <div class="field">
          <%= form.label :name %><br />
          <%= form.text_field :name, autofocus: true, autocomplete: "Name", disabled: "disabled", class: 'form-control' %>
        </div>

        <div class="field">
          <label for="profile_noofworkexyears">No of Years on Work Experience</label>
          <%= form.text_field :no_of_workex_years, id: :profile_noofworkexyears, class: 'form-control'%>
        </div>

        <div class="field">
          <label for="profile_current_company">Current Company</label>
          <%= form.text_field :current_company, id: :profile_current_company, class: 'form-control'%>
        </div>

        <div class="field">
          <label for="profile_resume">Please Upload Your resume</label>
          <%= form.file_field :attachment %>
        </div>
        <!--<div class="field">-->
          <!--<%= form.label :user_id %>-->
          <!--<%= form.text_field :user_id, id: :profile_user_id %>-->
        <!--</div>-->
        <%= form.submit 'Save Profile', class: 'btn btn-primary btn-lg btn-block'%>
      <% end %>
    </div>
  </div>
</div>
</div>