config/routes.rb
Rails.application.routes.draw do
  resources :applications
  match 'applications/:id/status', to: 'applications#status', via: 'get', as: :applications_status
  match '/users', to: 'users#index', via: 'get'
  resources :jobs
  resources :companies do
    end
  root to: 'pages#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
  devise_scope :user do
    get 'users/sign_in', to: 'devise/sessions#new'
  end
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
  match '/users/:id', to: 'users#destroy', via: 'delete', as: :user

  resources :profiles, only: [:index, :new, :create, :destroy, :edit, :update] do
  root "profiles#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company
  has_many :applications, dependent: :destroy
  def self.search(params)
    results = Job.all
    results = results.where(company_id: params[:company_id]) if params[:company_id].present?
    if params[:search].present?
      results = results.joins(:company).where('LOWER(companies.name) LIKE :search OR LOWER(companies.industry) LIKE :search OR LOWER(companies.hq) LIKE :search',search: "%#{params[:search]}%")
    end
    results
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /jobs
  # GET /jobs.json
  def index
      @jobs = Job.search(params)
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    unless !user_signed_in? or current_user.isAdmin? or current_user.isRecruiter?
      flash[:notice] = "Only admins can do that"
      redirect_to root_path
    end
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create

    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      if current_user.isAdmin?
        params.require(:job).permit(:position ,:job_description, :employment_type, :responsibilities, :requirements, :company_id).merge(user_id: current_user.id)
      else
        params.require(:job).permit(:position ,:job_description, :employment_type, :responsibilities, :requirements).merge(company_id: current_user.company_id).merge(user_id: current_user.id)
      end
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="container" id="job-form">
  <div class="row">
    <h4 class="text-center">Please add the given details</h4>

    <div class="col-sm-offset-4 col-sm-4">
  <%= bootstrap_form_for(@job) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position, id: :job_position %>
  </div>

  <div class="field">
    <%= form.label :job_description %>
    <%= form.text_field :job_description, id: :job_job_description %>
  </div>
        <% if current_user.isAdmin? %>
          <div class="field">
            <%= form.label :company_id %>
          <%= form.select :company_id, options_for_select(Company.all.map{ |c| [c.name, c.id]}), selected_key: [form.object.company, form.object.company_id]%>
          </div>
          <% end %>

  <div class="field">
    <%= form.label :employment_type %>
    <%= form.select :employment_type, ['Full Time', 'Internship', 'Co-op', 'Contract']%>
  </div>

  <div class="field">
    <%= form.label :responsibilities %>
    <%= form.text_field :responsibilities, id: :job_responsibilities %>
  </div>

  <div class="field">
    <%= form.label :requirements %>
    <%= form.text_field :requirements, id: :job_requirements %>
  </div>
        <%= form.hidden_field :isClosed, value: false%>

  <div class="actions">
    <%= form.submit 'Create Job', class: 'btn btn-primary btn-lg btn-block' %>
  </div>
<% end %>
    </div>
  </div>
</div>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>
<div class="container" id="job-form">
  <div class="row">
    <h4 class="text-center">Please edit the given details</h4>
    <div class="col-sm-offset-4 col-sm-4">
      <%= bootstrap_form_for(@job) do |form| %>
        <% if @job.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

            <ul>
              <% @job.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= form.label :position %>
          <%= form.text_field :position, id: :job_position %>
        </div>

        <div class="field">
          <%= form.label :job_description %>
          <%= form.text_field :job_description, id: :job_job_description %>
        </div>

        <div class="field">
          <%= form.label :employment_type %>
          <%= form.text_field :employment_type, id: :job_employment_type %>
        </div>

        <div class="field">
          <%= form.label :responsibilities %>
          <%= form.text_field :responsibilities, id: :job_responsibilities %>
        </div>

        <div class="field">
          <%= form.label :requirements %>
          <%= form.text_field :requirements, id: :job_requirements %>
        </div>

        <div class="field">
          <%= form.label :company_id %>
          <%= form.text_field :company_id, id: :job_company_id %>
        </div>

        <div class="actions">
          <%= form.submit 'Create Job', class: 'btn btn-primary btn-lg btn-block' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
<%= link_to 'Back to Jobs', jobs_path, class: 'btn btn-warning btn-lg' %>
</div>

app/views/jobs/index.html.erb
<h1>Jobs</h1>
<div class="container">
  <% if not Profile.exists?(user_id: current_user.id) %>
    <h5>Please update profile section before you can apply.</h5>
  <% end %>
  <div class="container container-fluid">
    <div class="col-sm-offset-9 col-sm-3 right">
      <% if current_user.isRecruiter? or current_user.isAdmin? %>
      <%= link_to 'New Job', new_job_path, class: 'btn btn-info btn-lg btn-block' %>
      <% end %>
    </div>
  </div>
</div>
<%= form_tag(request.env['PATH_INFO'], method: :get, :enforce_utf8 => false) do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', name: nil%>
<% end %>
<table class="table" style="table-layout: fixed; height: auto; overflow: auto">
  <thead>
    <tr>
      <th>Job ID</th>
      <th>Position</th>
      <th width="150px">Job description</th>
      <th>Employment type</th>
      <th width="150px">Responsibilities</th>
      <th width="150px">Requirements</th>
      <th>Company Name</th>
      <th>Open?</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
    <div id="display_jobs" class="list-group-item-text">
      <tr style="height: 100%; overflow: auto">
        <td><%= job.id %></td>
        <td><%= job.position %></td>
        <td style="overflow: hidden; text-overflow: ellipsis; height:auto;"><%= job.job_description%></td>
        <td><%= job.employment_type %></td>
        <td><%= job.responsibilities %></td>
        <td><%= job.requirements %></td>
        <td><%= job.company.name %></td>
        <%if not job.isClosed?%>
          <td><span class="fui-check" style="margin-left: 30%"></span></td>
        <% if job.user_id == current_user.id or (job.user_id==1 and current_user.companyname == job.company.name) or current_user.isAdmin?%>
          <td><%= link_to 'Show', job , class: 'btn btn-primary btn-lg btn-block' %></td>
        <% end %>
          <% if current_user.isRecruiter? and current_user.companyname == job.company.name%>
        <td><%= link_to 'Edit', edit_job_path(job), class: 'btn btn-warning btn-lg btn-block' %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-lg' %></td>
        <% elsif current_user.isAdmin? %>
          <td><%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-lg btn-block' %></td>
        <% elsif Profile.exists?(user_id: current_user.id) %>
          <td><%= link_to 'Apply', new_application_path(job_id: job.id), class: 'btn btn-warning btn-lg btn-block' %></td>
        <% end %>
          <% elsif (current_user.isRecruiter? and current_user.companyname == job.company.name ) or current_user.isAdmin? %>
          <td><span class="fui-cross" style="margin-left: 30%"></span></td>
          <td><%= link_to 'Show', job , class: 'btn btn-primary btn-lg btn-block' %></td>
          <%else%>
          <td><span class="fui-cross" style="margin-left: 30%"></span></td>
          <% end %>
      </tr>
    <% end %>
    </div>
  </tbody>
</table>

<br>

app/views/jobs/new.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center">Add a New Job</h2>

<%= render 'form', job: @job %>
    <div class="col-sm-offset-4 col-sm-4">
      <br>
      <br>
      <%= link_to 'Back', jobs_path, class: 'btn btn-warning btn-lg btn-block' %>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="container">
    <div class="row">

      <h2> <%= @job.position %> position at <%= @job.company.name %> </h2>

      <h3>Job ID:
        <%= @job.id%>
      </h3>


      <div class="col-sm-offset-4 col-sm-4">
<p style="overflow: auto; width: 100%; height: auto">
  <strong>Job description:</strong>
  <%= @job.job_description %>
</p>

<p>
  <strong>Employment type:</strong>
  <%= @job.employment_type %>
</p>

<p>
  <strong>Responsibilities:</strong>
  <%= @job.responsibilities %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @job.requirements %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company.name %>
</p>
        <% if (current_user.isRecruiter? and current_user.companyname == @job.company.name) or current_user.isAdmin?%>
<%= link_to 'Edit', edit_job_path(@job), class: 'btn btn-primary btn-lg' %>
        <% end %>
<%= link_to 'Back', jobs_path, class: 'btn btn-warning btn-lg'  %>
    </div>
  </div>
</div>
</div>

<% if Application.exists?(job_id: @job.id) %>
<h1>Applications</h1>
<%= form_tag(request.env['PATH_INFO'], method: :get, :enforce_utf8 => false) do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', name: nil%>
<% end %>
<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Current company</th>
    <th>Linkedin</th>
    <th>Add info</th>
    <th>Gender</th>
    <th>Race</th>
    <th>Disability</th>
    <th>Status</th>
    <th>Seeker Resume</th>
    <th>Actions</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% Application.all.where(job_id: @job.id).each do |application| %>
    <div class="list-group-item-text" id="display_applications">
      <tr>
        <td><%= application.name %></td>
        <td><%= application.current_company %></td>
        <td><%= application.linkedin %></td>
        <td><%= application.add_info %></td>
        <td><%= application.gender %></td>
        <td><%= application.race %></td>
        <td><%= application.disability %></td>
        <td><%= application.status %></td>
        <td><%= link_to 'Download Resume', Profile.find_by_user_id(application.user.id).attachment_url %></td>
        <% if not @job.isClosed?%>
        <td><%= link_to 'Select', applications_status_path(:job_id => application.job_id, :user_id => application.user.id), :controller => :applications , :action => :status, data: { confirm: 'Are You Sure for the Current Candidate?'}, class: 'btn btn-primary btn-lg btn-block' %></td>
        <td><%= link_to 'Remove', application, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-danger btn-lg btn-block' %></td>
          <% end %>
      </tr>
    </div>
  <% end %>
  </tbody>
</table>
<% end %>