config/routes.rb
Rails.application.routes.draw do
  resources :applications
  match 'applications/:id/status', to: 'applications#status', via: 'get', as: :applications_status
  match '/users', to: 'users#index', via: 'get'
  resources :jobs
  resources :companies do
    end
  root to: 'pages#index'
  devise_for :users, :controllers => {:registrations => "registrations"}
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end
  devise_scope :user do
    get 'users/sign_in', to: 'devise/sessions#new'
  end
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end
  match '/users/:id', to: 'users#destroy', via: 'delete', as: :user

  resources :profiles, only: [:index, :new, :create, :destroy, :edit, :update] do
  root "profiles#index"
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/helpers/navigation_helper.rb
module NavigationHelper
  def collapsible_links_partial_path
    if user_signed_in?
      'layouts/navigation/collapsible_elements/signed_in_links'
    else
      'layouts/navigation/collapsible_elements/non_signed_in_links'
    end
  end
end

app/views/layouts/navigation/collapsible_elements/_non_signed_in_links.html.erb
<li ><%= link_to 'Login', login_path %></li>
<li ><%= link_to 'Signup', signup_path %></li>

app/views/layouts/navigation/collapsible_elements/_signed_in_links.html.erb
<li><%= link_to 'Home', root_path, class: 'pc-menu'%></li>
<li><%= link_to 'Companies', companies_path , class: 'pc-menu'%></li>
<li><%= link_to 'Jobs', jobs_path , class: 'pc-menu'%></li>
<li><%= link_to 'Your Applications', applications_path , class: 'pc-menu'%></li>
<% if current_user.isAdmin?%>
  <li><%= link_to 'Users', users_path, class: 'pc-menu'%></li>
<% end %>
<li class="dropdown pc-menu">
  <a id="user-settings" class="dropdown-toggle" data-toggle="dropdown" href="#">
    <span id="user-name"><%= current_user.name %></span>
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li><%= link_to 'Show Profile', profiles_path %></li>
    <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
    <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
  </ul>
</li>

<li class="mobile-menu">
  <%= link_to 'Home', root_path %>
  <%= link_to 'Companies', companies_path %>
  <%= link_to 'Jobs', companies_path %>
<%= link_to 'Your Applications', applications_path%>
  <% if current_user.isAdmin?%>
    <%= link_to 'Users', users_path%>
  <% end %>
  <%= link_to 'Edit Account', edit_user_registration_path %>
</li>
<li class="mobile-menu">
  <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
</li>